/*
 * Komga API
 *
 * Komga offers 2 APIs: REST and OPDS.  Both APIs are secured using HTTP Basic Authentication.
 *
 * The version of the OpenAPI document: v1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AgeRestrictionDto {
    #[serde(rename = "age")]
    pub age: i32,
    #[serde(rename = "restriction")]
    pub restriction: Restriction,
}

impl AgeRestrictionDto {
    pub fn new(age: i32, restriction: Restriction) -> AgeRestrictionDto {
        AgeRestrictionDto {
            age,
            restriction,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Restriction {
    #[serde(rename = "ALLOW_ONLY")]
    AllowOnly,
    #[serde(rename = "EXCLUDE")]
    Exclude,
}

impl Default for Restriction {
    fn default() -> Restriction {
        Self::AllowOnly
    }
}

