/*
 * Komga API
 *
 * Komga offers 2 APIs: REST and OPDS.  Both APIs are secured using HTTP Basic Authentication.
 *
 * The version of the OpenAPI document: v1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AlternateTitleUpdateDto {
    #[serde(rename = "label")]
    pub label: String,
    #[serde(rename = "title")]
    pub title: String,
}

impl AlternateTitleUpdateDto {
    pub fn new(label: String, title: String) -> AlternateTitleUpdateDto {
        AlternateTitleUpdateDto {
            label,
            title,
        }
    }
}


