/*
 * Komga API
 *
 * Komga offers 2 APIs: REST and OPDS.  Both APIs are secured using HTTP Basic Authentication.
 *
 * The version of the OpenAPI document: v1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BookMetadataDto {
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "titleLock")]
    pub title_lock: bool,
    #[serde(rename = "summary")]
    pub summary: String,
    #[serde(rename = "summaryLock")]
    pub summary_lock: bool,
    #[serde(rename = "number")]
    pub number: String,
    #[serde(rename = "numberLock")]
    pub number_lock: bool,
    #[serde(rename = "numberSort")]
    pub number_sort: f32,
    #[serde(rename = "numberSortLock")]
    pub number_sort_lock: bool,
    #[serde(rename = "releaseDate", skip_serializing_if = "Option::is_none")]
    pub release_date: Option<String>,
    #[serde(rename = "releaseDateLock")]
    pub release_date_lock: bool,
    #[serde(rename = "authors")]
    pub authors: Vec<crate::models::AuthorDto>,
    #[serde(rename = "authorsLock")]
    pub authors_lock: bool,
    #[serde(rename = "tags")]
    pub tags: Vec<String>,
    #[serde(rename = "tagsLock")]
    pub tags_lock: bool,
    #[serde(rename = "isbn")]
    pub isbn: String,
    #[serde(rename = "isbnLock")]
    pub isbn_lock: bool,
    #[serde(rename = "links")]
    pub links: Vec<crate::models::WebLinkDto>,
    #[serde(rename = "linksLock")]
    pub links_lock: bool,
    #[serde(rename = "created")]
    pub created: String,
    #[serde(rename = "lastModified")]
    pub last_modified: String,
}

impl BookMetadataDto {
    pub fn new(title: String, title_lock: bool, summary: String, summary_lock: bool, number: String, number_lock: bool, number_sort: f32, number_sort_lock: bool, release_date_lock: bool, authors: Vec<crate::models::AuthorDto>, authors_lock: bool, tags: Vec<String>, tags_lock: bool, isbn: String, isbn_lock: bool, links: Vec<crate::models::WebLinkDto>, links_lock: bool, created: String, last_modified: String) -> BookMetadataDto {
        BookMetadataDto {
            title,
            title_lock,
            summary,
            summary_lock,
            number,
            number_lock,
            number_sort,
            number_sort_lock,
            release_date: None,
            release_date_lock,
            authors,
            authors_lock,
            tags,
            tags_lock,
            isbn,
            isbn_lock,
            links,
            links_lock,
            created,
            last_modified,
        }
    }
}


