/*
 * Komga API
 *
 * Komga offers 2 APIs: REST and OPDS.  Both APIs are secured using HTTP Basic Authentication.
 *
 * The version of the OpenAPI document: v1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// BookMetadataUpdateDto : Metadata fields to update. Set a field to null to unset the metadata. You can omit fields you don't want to update.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BookMetadataUpdateDto {
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(rename = "titleLock", skip_serializing_if = "Option::is_none")]
    pub title_lock: Option<bool>,
    #[serde(rename = "summaryLock", skip_serializing_if = "Option::is_none")]
    pub summary_lock: Option<bool>,
    #[serde(rename = "number", skip_serializing_if = "Option::is_none")]
    pub number: Option<String>,
    #[serde(rename = "numberLock", skip_serializing_if = "Option::is_none")]
    pub number_lock: Option<bool>,
    #[serde(rename = "numberSort", skip_serializing_if = "Option::is_none")]
    pub number_sort: Option<f32>,
    #[serde(rename = "numberSortLock", skip_serializing_if = "Option::is_none")]
    pub number_sort_lock: Option<bool>,
    #[serde(rename = "releaseDateLock", skip_serializing_if = "Option::is_none")]
    pub release_date_lock: Option<bool>,
    #[serde(rename = "authorsLock", skip_serializing_if = "Option::is_none")]
    pub authors_lock: Option<bool>,
    #[serde(rename = "tagsLock", skip_serializing_if = "Option::is_none")]
    pub tags_lock: Option<bool>,
    #[serde(rename = "isbnLock", skip_serializing_if = "Option::is_none")]
    pub isbn_lock: Option<bool>,
    #[serde(rename = "linksLock", skip_serializing_if = "Option::is_none")]
    pub links_lock: Option<bool>,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
    #[serde(rename = "isbn", skip_serializing_if = "Option::is_none")]
    pub isbn: Option<String>,
    #[serde(rename = "links", skip_serializing_if = "Option::is_none")]
    pub links: Option<Vec<crate::models::WebLinkUpdateDto>>,
    #[serde(rename = "authors", skip_serializing_if = "Option::is_none")]
    pub authors: Option<Vec<crate::models::AuthorUpdateDto>>,
    #[serde(rename = "summary", skip_serializing_if = "Option::is_none")]
    pub summary: Option<String>,
    #[serde(rename = "releaseDate", skip_serializing_if = "Option::is_none")]
    pub release_date: Option<String>,
}

impl BookMetadataUpdateDto {
    /// Metadata fields to update. Set a field to null to unset the metadata. You can omit fields you don't want to update.
    pub fn new() -> BookMetadataUpdateDto {
        BookMetadataUpdateDto {
            title: None,
            title_lock: None,
            summary_lock: None,
            number: None,
            number_lock: None,
            number_sort: None,
            number_sort_lock: None,
            release_date_lock: None,
            authors_lock: None,
            tags_lock: None,
            isbn_lock: None,
            links_lock: None,
            tags: None,
            isbn: None,
            links: None,
            authors: None,
            summary: None,
            release_date: None,
        }
    }
}


