/*
 * Komga API
 *
 * Komga offers 2 APIs: REST and OPDS.  Both APIs are secured using HTTP Basic Authentication.
 *
 * The version of the OpenAPI document: v1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BookImportDto {
    #[serde(rename = "sourceFile")]
    pub source_file: String,
    #[serde(rename = "seriesId")]
    pub series_id: String,
    #[serde(rename = "upgradeBookId", skip_serializing_if = "Option::is_none")]
    pub upgrade_book_id: Option<String>,
    #[serde(rename = "destinationName", skip_serializing_if = "Option::is_none")]
    pub destination_name: Option<String>,
}

impl BookImportDto {
    pub fn new(source_file: String, series_id: String) -> BookImportDto {
        BookImportDto {
            source_file,
            series_id,
            upgrade_book_id: None,
            destination_name: None,
        }
    }
}


