/*
 * Komga API
 *
 * Komga offers 2 APIs: REST and OPDS.  Both APIs are secured using HTTP Basic Authentication.
 *
 * The version of the OpenAPI document: v1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BookImportBatchDto {
    #[serde(rename = "books")]
    pub books: Vec<crate::models::BookImportDto>,
    #[serde(rename = "copyMode")]
    pub copy_mode: CopyMode,
}

impl BookImportBatchDto {
    pub fn new(books: Vec<crate::models::BookImportDto>, copy_mode: CopyMode) -> BookImportBatchDto {
        BookImportBatchDto {
            books,
            copy_mode,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CopyMode {
    #[serde(rename = "MOVE")]
    Move,
    #[serde(rename = "COPY")]
    Copy,
    #[serde(rename = "HARDLINK")]
    Hardlink,
}

impl Default for CopyMode {
    fn default() -> CopyMode {
        Self::Move
    }
}

