/*
 * Komga API
 *
 * Komga offers 2 APIs: REST and OPDS.  Both APIs are secured using HTTP Basic Authentication.
 *
 * The version of the OpenAPI document: v1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClaimStatus {
    #[serde(rename = "isClaimed")]
    pub is_claimed: bool,
}

impl ClaimStatus {
    pub fn new(is_claimed: bool) -> ClaimStatus {
        ClaimStatus {
            is_claimed,
        }
    }
}


