/*
 * Komga API
 *
 * Komga offers 2 APIs: REST and OPDS.  Both APIs are secured using HTTP Basic Authentication.
 *
 * The version of the OpenAPI document: v1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CollectionCreationDto {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "ordered")]
    pub ordered: bool,
    #[serde(rename = "seriesIds")]
    pub series_ids: Vec<String>,
}

impl CollectionCreationDto {
    pub fn new(name: String, ordered: bool, series_ids: Vec<String>) -> CollectionCreationDto {
        CollectionCreationDto {
            name,
            ordered,
            series_ids,
        }
    }
}


