/*
 * Komga API
 *
 * Komga offers 2 APIs: REST and OPDS.  Both APIs are secured using HTTP Basic Authentication.
 *
 * The version of the OpenAPI document: v1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CollectionUpdateDto {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "ordered", skip_serializing_if = "Option::is_none")]
    pub ordered: Option<bool>,
    #[serde(rename = "seriesIds", skip_serializing_if = "Option::is_none")]
    pub series_ids: Option<Vec<String>>,
}

impl CollectionUpdateDto {
    pub fn new() -> CollectionUpdateDto {
        CollectionUpdateDto {
            name: None,
            ordered: None,
            series_ids: None,
        }
    }
}


