/*
 * Komga API
 *
 * Komga offers 2 APIs: REST and OPDS.  Both APIs are secured using HTTP Basic Authentication.
 *
 * The version of the OpenAPI document: v1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DirectoryListingDto {
    #[serde(rename = "parent", skip_serializing_if = "Option::is_none")]
    pub parent: Option<String>,
    #[serde(rename = "directories")]
    pub directories: Vec<crate::models::PathDto>,
}

impl DirectoryListingDto {
    pub fn new(directories: Vec<crate::models::PathDto>) -> DirectoryListingDto {
        DirectoryListingDto {
            parent: None,
            directories,
        }
    }
}


