/*
 * Komga API
 *
 * Komga offers 2 APIs: REST and OPDS.  Both APIs are secured using HTTP Basic Authentication.
 *
 * The version of the OpenAPI document: v1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GroupCountDto {
    #[serde(rename = "group")]
    pub group: String,
    #[serde(rename = "count")]
    pub count: i32,
}

impl GroupCountDto {
    pub fn new(group: String, count: i32) -> GroupCountDto {
        GroupCountDto {
            group,
            count,
        }
    }
}


