/*
 * Komga API
 *
 * Komga offers 2 APIs: REST and OPDS.  Both APIs are secured using HTTP Basic Authentication.
 *
 * The version of the OpenAPI document: v1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct HistoricalEventDto {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "timestamp")]
    pub timestamp: String,
    #[serde(rename = "bookId", skip_serializing_if = "Option::is_none")]
    pub book_id: Option<String>,
    #[serde(rename = "seriesId", skip_serializing_if = "Option::is_none")]
    pub series_id: Option<String>,
    #[serde(rename = "properties")]
    pub properties: ::std::collections::HashMap<String, String>,
}

impl HistoricalEventDto {
    pub fn new(r#type: String, timestamp: String, properties: ::std::collections::HashMap<String, String>) -> HistoricalEventDto {
        HistoricalEventDto {
            r#type,
            timestamp,
            book_id: None,
            series_id: None,
            properties,
        }
    }
}


