/*
 * Komga API
 *
 * Komga offers 2 APIs: REST and OPDS.  Both APIs are secured using HTTP Basic Authentication.
 *
 * The version of the OpenAPI document: v1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct JsonFeedDto {
    #[serde(rename = "version")]
    pub version: String,
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "home_page_url", skip_serializing_if = "Option::is_none")]
    pub home_page_url: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "items")]
    pub items: Vec<crate::models::ItemDto>,
}

impl JsonFeedDto {
    pub fn new(version: String, title: String, items: Vec<crate::models::ItemDto>) -> JsonFeedDto {
        JsonFeedDto {
            version,
            title,
            home_page_url: None,
            description: None,
            items,
        }
    }
}


