/*
 * Komga API
 *
 * Komga offers 2 APIs: REST and OPDS.  Both APIs are secured using HTTP Basic Authentication.
 *
 * The version of the OpenAPI document: v1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Location {
    #[serde(rename = "fragments")]
    pub fragments: Vec<String>,
    #[serde(rename = "progression", skip_serializing_if = "Option::is_none")]
    pub progression: Option<f32>,
    #[serde(rename = "position", skip_serializing_if = "Option::is_none")]
    pub position: Option<i32>,
    #[serde(rename = "totalProgression", skip_serializing_if = "Option::is_none")]
    pub total_progression: Option<f32>,
}

impl Location {
    pub fn new(fragments: Vec<String>) -> Location {
        Location {
            fragments,
            progression: None,
            position: None,
            total_progression: None,
        }
    }
}


