/*
 * Komga API
 *
 * Komga offers 2 APIs: REST and OPDS.  Both APIs are secured using HTTP Basic Authentication.
 *
 * The version of the OpenAPI document: v1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MediaDto {
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "mediaType")]
    pub media_type: String,
    #[serde(rename = "pagesCount")]
    pub pages_count: i32,
    #[serde(rename = "comment")]
    pub comment: String,
    #[serde(rename = "epubDivinaCompatible")]
    pub epub_divina_compatible: bool,
    #[serde(rename = "mediaProfile")]
    pub media_profile: String,
}

impl MediaDto {
    pub fn new(status: String, media_type: String, pages_count: i32, comment: String, epub_divina_compatible: bool, media_profile: String) -> MediaDto {
        MediaDto {
            status,
            media_type,
            pages_count,
            comment,
            epub_divina_compatible,
            media_profile,
        }
    }
}


