/*
 * Komga API
 *
 * Komga offers 2 APIs: REST and OPDS.  Both APIs are secured using HTTP Basic Authentication.
 *
 * The version of the OpenAPI document: v1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PageableObject {
    #[serde(rename = "offset", skip_serializing_if = "Option::is_none")]
    pub offset: Option<i64>,
    #[serde(rename = "sort", skip_serializing_if = "Option::is_none")]
    pub sort: Option<Box<crate::models::SortObject>>,
    #[serde(rename = "pageNumber", skip_serializing_if = "Option::is_none")]
    pub page_number: Option<i32>,
    #[serde(rename = "pageSize", skip_serializing_if = "Option::is_none")]
    pub page_size: Option<i32>,
    #[serde(rename = "paged", skip_serializing_if = "Option::is_none")]
    pub paged: Option<bool>,
    #[serde(rename = "unpaged", skip_serializing_if = "Option::is_none")]
    pub unpaged: Option<bool>,
}

impl PageableObject {
    pub fn new() -> PageableObject {
        PageableObject {
            offset: None,
            sort: None,
            page_number: None,
            page_size: None,
            paged: None,
            unpaged: None,
        }
    }
}


