/*
 * Komga API
 *
 * Komga offers 2 APIs: REST and OPDS.  Both APIs are secured using HTTP Basic Authentication.
 *
 * The version of the OpenAPI document: v1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PageDto {
    #[serde(rename = "number")]
    pub number: i32,
    #[serde(rename = "fileName")]
    pub file_name: String,
    #[serde(rename = "mediaType")]
    pub media_type: String,
    #[serde(rename = "width", skip_serializing_if = "Option::is_none")]
    pub width: Option<i32>,
    #[serde(rename = "height", skip_serializing_if = "Option::is_none")]
    pub height: Option<i32>,
    #[serde(rename = "sizeBytes", skip_serializing_if = "Option::is_none")]
    pub size_bytes: Option<i64>,
    #[serde(rename = "size")]
    pub size: String,
}

impl PageDto {
    pub fn new(number: i32, file_name: String, media_type: String, size: String) -> PageDto {
        PageDto {
            number,
            file_name,
            media_type,
            width: None,
            height: None,
            size_bytes: None,
            size,
        }
    }
}


