/*
 * Komga API
 *
 * Komga offers 2 APIs: REST and OPDS.  Both APIs are secured using HTTP Basic Authentication.
 *
 * The version of the OpenAPI document: v1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PageHashUnknownDto {
    #[serde(rename = "hash")]
    pub hash: String,
    #[serde(rename = "size", skip_serializing_if = "Option::is_none")]
    pub size: Option<i64>,
    #[serde(rename = "matchCount")]
    pub match_count: i32,
}

impl PageHashUnknownDto {
    pub fn new(hash: String, match_count: i32) -> PageHashUnknownDto {
        PageHashUnknownDto {
            hash,
            size: None,
            match_count,
        }
    }
}


