/*
 * Komga API
 *
 * Komga offers 2 APIs: REST and OPDS.  Both APIs are secured using HTTP Basic Authentication.
 *
 * The version of the OpenAPI document: v1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PageHashMatchDto {
    #[serde(rename = "bookId")]
    pub book_id: String,
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "pageNumber")]
    pub page_number: i32,
    #[serde(rename = "fileName")]
    pub file_name: String,
    #[serde(rename = "fileSize")]
    pub file_size: i64,
    #[serde(rename = "mediaType")]
    pub media_type: String,
}

impl PageHashMatchDto {
    pub fn new(book_id: String, url: String, page_number: i32, file_name: String, file_size: i64, media_type: String) -> PageHashMatchDto {
        PageHashMatchDto {
            book_id,
            url,
            page_number,
            file_name,
            file_size,
            media_type,
        }
    }
}


