/*
 * Komga API
 *
 * Komga offers 2 APIs: REST and OPDS.  Both APIs are secured using HTTP Basic Authentication.
 *
 * The version of the OpenAPI document: v1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PasswordUpdateDto {
    #[serde(rename = "password")]
    pub password: String,
}

impl PasswordUpdateDto {
    pub fn new(password: String) -> PasswordUpdateDto {
        PasswordUpdateDto {
            password,
        }
    }
}


