/*
 * Komga API
 *
 * Komga offers 2 APIs: REST and OPDS.  Both APIs are secured using HTTP Basic Authentication.
 *
 * The version of the OpenAPI document: v1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PathDto {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "path")]
    pub path: String,
}

impl PathDto {
    pub fn new(r#type: String, name: String, path: String) -> PathDto {
        PathDto {
            r#type,
            name,
            path,
        }
    }
}


