/*
 * Komga API
 *
 * Komga offers 2 APIs: REST and OPDS.  Both APIs are secured using HTTP Basic Authentication.
 *
 * The version of the OpenAPI document: v1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct R2Locator {
    #[serde(rename = "href")]
    pub href: String,
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(rename = "locations", skip_serializing_if = "Option::is_none")]
    pub locations: Option<Box<crate::models::Location>>,
    #[serde(rename = "text", skip_serializing_if = "Option::is_none")]
    pub text: Option<Box<crate::models::Text>>,
}

impl R2Locator {
    pub fn new(href: String, r#type: String) -> R2Locator {
        R2Locator {
            href,
            r#type,
            title: None,
            locations: None,
            text: None,
        }
    }
}


