/*
 * Komga API
 *
 * Komga offers 2 APIs: REST and OPDS.  Both APIs are secured using HTTP Basic Authentication.
 *
 * The version of the OpenAPI document: v1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct R2Progression {
    #[serde(rename = "modified")]
    pub modified: String,
    #[serde(rename = "device")]
    pub device: Box<crate::models::R2Device>,
    #[serde(rename = "locator")]
    pub locator: Box<crate::models::R2Locator>,
}

impl R2Progression {
    pub fn new(modified: String, device: crate::models::R2Device, locator: crate::models::R2Locator) -> R2Progression {
        R2Progression {
            modified,
            device: Box::new(device),
            locator: Box::new(locator),
        }
    }
}


