/*
 * Komga API
 *
 * Komga offers 2 APIs: REST and OPDS.  Both APIs are secured using HTTP Basic Authentication.
 *
 * The version of the OpenAPI document: v1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReadListRequestMatchDto {
    #[serde(rename = "readListMatch")]
    pub read_list_match: Box<crate::models::ReadListMatchDto>,
    #[serde(rename = "requests")]
    pub requests: Vec<crate::models::ReadListRequestBookMatchesDto>,
    #[serde(rename = "errorCode")]
    pub error_code: String,
}

impl ReadListRequestMatchDto {
    pub fn new(read_list_match: crate::models::ReadListMatchDto, requests: Vec<crate::models::ReadListRequestBookMatchesDto>, error_code: String) -> ReadListRequestMatchDto {
        ReadListRequestMatchDto {
            read_list_match: Box::new(read_list_match),
            requests,
            error_code,
        }
    }
}


