/*
 * Komga API
 *
 * Komga offers 2 APIs: REST and OPDS.  Both APIs are secured using HTTP Basic Authentication.
 *
 * The version of the OpenAPI document: v1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReadListCreationDto {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "summary")]
    pub summary: String,
    #[serde(rename = "ordered")]
    pub ordered: bool,
    #[serde(rename = "bookIds")]
    pub book_ids: Vec<String>,
}

impl ReadListCreationDto {
    pub fn new(name: String, summary: String, ordered: bool, book_ids: Vec<String>) -> ReadListCreationDto {
        ReadListCreationDto {
            name,
            summary,
            ordered,
            book_ids,
        }
    }
}


