/*
 * Komga API
 *
 * Komga offers 2 APIs: REST and OPDS.  Both APIs are secured using HTTP Basic Authentication.
 *
 * The version of the OpenAPI document: v1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReadListRequestBookMatchDto {
    #[serde(rename = "series")]
    pub series: Box<crate::models::ReadListRequestBookMatchSeriesDto>,
    #[serde(rename = "books")]
    pub books: Vec<crate::models::ReadListRequestBookMatchBookDto>,
}

impl ReadListRequestBookMatchDto {
    pub fn new(series: crate::models::ReadListRequestBookMatchSeriesDto, books: Vec<crate::models::ReadListRequestBookMatchBookDto>) -> ReadListRequestBookMatchDto {
        ReadListRequestBookMatchDto {
            series: Box::new(series),
            books,
        }
    }
}


