/*
 * Komga API
 *
 * Komga offers 2 APIs: REST and OPDS.  Both APIs are secured using HTTP Basic Authentication.
 *
 * The version of the OpenAPI document: v1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReadListRequestBookMatchSeriesDto {
    #[serde(rename = "seriesId")]
    pub series_id: String,
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "releaseDate", skip_serializing_if = "Option::is_none")]
    pub release_date: Option<String>,
}

impl ReadListRequestBookMatchSeriesDto {
    pub fn new(series_id: String, title: String) -> ReadListRequestBookMatchSeriesDto {
        ReadListRequestBookMatchSeriesDto {
            series_id,
            title,
            release_date: None,
        }
    }
}


