/*
 * Komga API
 *
 * Komga offers 2 APIs: REST and OPDS.  Both APIs are secured using HTTP Basic Authentication.
 *
 * The version of the OpenAPI document: v1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReadProgressDto {
    #[serde(rename = "page")]
    pub page: i32,
    #[serde(rename = "completed")]
    pub completed: bool,
    #[serde(rename = "readDate")]
    pub read_date: String,
    #[serde(rename = "created")]
    pub created: String,
    #[serde(rename = "lastModified")]
    pub last_modified: String,
    #[serde(rename = "deviceId")]
    pub device_id: String,
    #[serde(rename = "deviceName")]
    pub device_name: String,
}

impl ReadProgressDto {
    pub fn new(page: i32, completed: bool, read_date: String, created: String, last_modified: String, device_id: String, device_name: String) -> ReadProgressDto {
        ReadProgressDto {
            page,
            completed,
            read_date,
            created,
            last_modified,
            device_id,
            device_name,
        }
    }
}


