/*
 * Komga API
 *
 * Komga offers 2 APIs: REST and OPDS.  Both APIs are secured using HTTP Basic Authentication.
 *
 * The version of the OpenAPI document: v1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReadListMatchDto {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "errorCode")]
    pub error_code: String,
}

impl ReadListMatchDto {
    pub fn new(name: String, error_code: String) -> ReadListMatchDto {
        ReadListMatchDto {
            name,
            error_code,
        }
    }
}


