/*
 * Komga API
 *
 * Komga offers 2 APIs: REST and OPDS.  Both APIs are secured using HTTP Basic Authentication.
 *
 * The version of the OpenAPI document: v1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SettingMultiSourceInteger {
    #[serde(rename = "configurationSource")]
    pub configuration_source: i32,
    #[serde(rename = "databaseSource")]
    pub database_source: i32,
    #[serde(rename = "effectiveValue")]
    pub effective_value: i32,
}

impl SettingMultiSourceInteger {
    pub fn new(configuration_source: i32, database_source: i32, effective_value: i32) -> SettingMultiSourceInteger {
        SettingMultiSourceInteger {
            configuration_source,
            database_source,
            effective_value,
        }
    }
}


