/*
 * Komga API
 *
 * Komga offers 2 APIs: REST and OPDS.  Both APIs are secured using HTTP Basic Authentication.
 *
 * The version of the OpenAPI document: v1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SettingMultiSourceString {
    #[serde(rename = "configurationSource")]
    pub configuration_source: String,
    #[serde(rename = "databaseSource")]
    pub database_source: String,
    #[serde(rename = "effectiveValue")]
    pub effective_value: String,
}

impl SettingMultiSourceString {
    pub fn new(configuration_source: String, database_source: String, effective_value: String) -> SettingMultiSourceString {
        SettingMultiSourceString {
            configuration_source,
            database_source,
            effective_value,
        }
    }
}


