/*
 * Komga API
 *
 * Komga offers 2 APIs: REST and OPDS.  Both APIs are secured using HTTP Basic Authentication.
 *
 * The version of the OpenAPI document: v1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SharedLibrariesUpdateDto {
    #[serde(rename = "all")]
    pub all: bool,
    #[serde(rename = "libraryIds")]
    pub library_ids: Vec<String>,
}

impl SharedLibrariesUpdateDto {
    pub fn new(all: bool, library_ids: Vec<String>) -> SharedLibrariesUpdateDto {
        SharedLibrariesUpdateDto {
            all,
            library_ids,
        }
    }
}


