/*
 * Komga API
 *
 * Komga offers 2 APIs: REST and OPDS.  Both APIs are secured using HTTP Basic Authentication.
 *
 * The version of the OpenAPI document: v1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TachiyomiReadProgressUpdateV2Dto {
    #[serde(rename = "lastBookNumberSortRead")]
    pub last_book_number_sort_read: f32,
}

impl TachiyomiReadProgressUpdateV2Dto {
    pub fn new(last_book_number_sort_read: f32) -> TachiyomiReadProgressUpdateV2Dto {
        TachiyomiReadProgressUpdateV2Dto {
            last_book_number_sort_read,
        }
    }
}


