/*
 * Komga API
 *
 * Komga offers 2 APIs: REST and OPDS.  Both APIs are secured using HTTP Basic Authentication.
 *
 * The version of the OpenAPI document: v1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TachiyomiReadProgressUpdateDto {
    #[serde(rename = "lastBookRead")]
    pub last_book_read: i32,
}

impl TachiyomiReadProgressUpdateDto {
    pub fn new(last_book_read: i32) -> TachiyomiReadProgressUpdateDto {
        TachiyomiReadProgressUpdateDto {
            last_book_read,
        }
    }
}


