/*
 * Komga API
 *
 * Komga offers 2 APIs: REST and OPDS.  Both APIs are secured using HTTP Basic Authentication.
 *
 * The version of the OpenAPI document: v1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ValidationErrorResponse {
    #[serde(rename = "violations")]
    pub violations: Vec<crate::models::Violation>,
}

impl ValidationErrorResponse {
    pub fn new(violations: Vec<crate::models::Violation>) -> ValidationErrorResponse {
        ValidationErrorResponse {
            violations,
        }
    }
}


