/*
 * Komga API
 *
 * Komga offers 2 APIs: REST and OPDS.  Both APIs are secured using HTTP Basic Authentication.
 *
 * The version of the OpenAPI document: v1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebLinkDto {
    #[serde(rename = "label")]
    pub label: String,
    #[serde(rename = "url")]
    pub url: String,
}

impl WebLinkDto {
    pub fn new(label: String, url: String) -> WebLinkDto {
        WebLinkDto {
            label,
            url,
        }
    }
}


