/*
 * Komga API
 *
 * Komga offers 2 APIs: REST and OPDS.  Both APIs are secured using HTTP Basic Authentication.
 *
 * The version of the OpenAPI document: v1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebLinkUpdateDto {
    #[serde(rename = "label")]
    pub label: String,
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
}

impl WebLinkUpdateDto {
    pub fn new(label: String) -> WebLinkUpdateDto {
        WebLinkUpdateDto {
            label,
            url: None,
        }
    }
}


