/*
 * Komga API
 *
 * Komga offers 2 APIs: REST and OPDS.  Both APIs are secured using HTTP Basic Authentication.
 *
 * The version of the OpenAPI document: v1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct WpBelongsToDto {
    #[serde(rename = "series")]
    pub series: Vec<crate::models::WpContributorDto>,
    #[serde(rename = "collection")]
    pub collection: Vec<crate::models::WpContributorDto>,
}

impl WpBelongsToDto {
    pub fn new(series: Vec<crate::models::WpContributorDto>, collection: Vec<crate::models::WpContributorDto>) -> WpBelongsToDto {
        WpBelongsToDto {
            series,
            collection,
        }
    }
}


